### PR TITLE
fix a compile error on 32-bit (fixes #634)

### LINKED ISSUE #634: missing _mm_crc32_u64 on 32 bit build
On an Ubuntu 14.04.2 32 bit system with gcc 4.8.2, I get the following build error:

```
util/crc32c.cc: In function ‘void rocksdb::crc32c::Fast_CRC32(uint64_t*, const uint8_t**)’:
util/crc32c.cc:318:39: error: ‘_mm_crc32_u64’ was not declared in this scope
   *l = _mm_crc32_u64(*l, LE_LOAD64(*p));
```

I don't know if it is supposed to exist on a 32 bit system or not, but `__SSE4_2__` is defined, so the code assumes it exists.

### PR DESCRIPTION
**Pull request by warrenfalk**
This fixes the compile error on 32-bit mentioned in issue #634.  This allows successful compilation of 32 bit library on Linux.

Debug compilation on OSX still fails because it declares -Wshorten-64-to-32, so you have to turn off warnings as errors to compile.  It does compile after that.

Note that it doesn't appear that the test cases were operational in 32 bit, so I can't evaluate whether any test cases fail as a result of this change.

### CODE REVIEW

File: util/crc32c.cc [hunk 1]
```diff
@@ -315,9 +315,16 @@ static inline void Slow_CRC32(uint64_t* l, uint8_t const **p) {
 
 static inline void Fast_CRC32(uint64_t* l, uint8_t const **p) {
 #ifdef __SSE4_2__
+#ifdef __LP64__
   *l = _mm_crc32_u64(*l, LE_LOAD64(*p));
   *p += 8;
 #else
+  *l = _mm_crc32_u32(*l, LE_LOAD32(*p));
+  *p += 4;
+  *l = _mm_crc32_u32(*l, LE_LOAD32(*p));
```
Comment (igorcanadi) [inline util/crc32c.cc]: Hm, do you also have to `l = ((char*)l)+4`?

Can you make sure that crc32 returns the same result in 32-bit mode as in 64-bit?

Comment (warrenfalk) [inline util/crc32c.cc]: I don't think so.  If I understand your question correctly, you're wondering if I need to advance the ```l``` pointer for the next 32 bits.  The answer is no because despite ```_mm_crc32_u64``` taking a ````uint64_t*```` as its first argument, it only ever sets the lower 32 bits of that.

I did verify that this returns the same results in 64 bit and 32 bit.  Note, however, I don't have a big-endian machine to test on, so I can't verify that.

Also, I was able to run the crc32c_test which also passes.

However, it does result in a compiler warning that I somehow missed.  So please wait for an updated commit.

Comment (warrenfalk) [inline util/crc32c.cc]: OK, additional commit to fix compiler warning.

Let me know if you prefer them squashed.

File: util/crc32c.cc [hunk 2]
```diff
@@ -315,9 +315,16 @@ static inline void Slow_CRC32(uint64_t* l, uint8_t const **p) {
 
 static inline void Fast_CRC32(uint64_t* l, uint8_t const **p) {
 #ifdef __SSE4_2__
+#ifdef __LP64__
   *l = _mm_crc32_u64(*l, LE_LOAD64(*p));
   *p += 8;
 #else
+  *l = _mm_crc32_u32((unsigned int)*l, LE_LOAD32(*p));
+  *p += 4;
+  *l = _mm_crc32_u32((unsigned int)*l, LE_LOAD32(*p));
```
Comment (igorcanadi) [inline util/crc32c.cc]: Can you please use static_cast<unsigned int>(*l). We prefer C++ style casts to C style casts in RocksDB codebase.

Comment (warrenfalk) [inline util/crc32c.cc]: Added static_cast in a new commit

**Comment by warrenfalk** [comment]
Note: there was also an unused function warning in 32-bit mode for ```LE_LOAD64``` no longer being used so I added a follow-up commit in which I wrapped its declaration in an extra ```#ifdef````.

**Comment by igorcanadi** [comment]
Makes sense, thanks. I'm happy to land this, but I'd like to get couple of more eyeballs on this. Crc32s are persisted data, and it's important for them to be matching on all combinations of (32, 64) bit and (little, big) endian. Once we land this there's no rollback, so we have to be extra certain this is correct.

**Comment by siying** [comment]
I don't know who is the expert that can help review this PR. Maybe ask it our public group?

**Comment by igorcanadi** [comment]
We got confirmation that this is the correct implementation, so I'm merging this. Thanks @warrenfalk !

**Comment by igorcanadi** [comment]
BTW you should note that we still don't fully support 32-bit version and you're on your own. If we decide to support it, we'll first need to setup a 32-bit continuous build to make sure it keeps working.

**Comment by warrenfalk** [comment]
Cool.  Disclaimer noted and in fact, I'm pretty sure 32 bit doesn't currently work; it fails dbtest pretty immediately.  But now at least it builds, so maybe someone who cares enough will have more time to look at it.  Perhaps I will look at it some day.  As far as I can tell, even if 32-bit does work, I suspect it may not handle databases over certain size thresholds because of a pervasive use of uint64_t variables for offsets in in-memory structures.
